### ISSUE TITLE
Support for API Key Authentication

### ISSUE THREAD

**Issue by freak3dot** [spacenate/surveygizmo-api-php#6]
Survey gizmo no longer supports user $userId and $secret authentication.

> "The API password and hash authentication options were officially deprecated effective May 31, 2016. API calls using either method will no longer function."

https://apihelp.surveygizmo.com/help/authentication

https://community.surveygizmo.com/questions/question/final-notice-surveygizmo-api-authentication-changes/

**Comment by freak3dot** [comment]
Looks like testCredentialTypeDefaultsToPass unit test is failing as a direct result of this change.

**Comment by freak3dot** [comment]
In case anyone else stumbles across this in the future, You can still initialize this repo with the new authentication.

`new SurveyGizmoApiWrapper($userId = surveygizmo.key, $secret = null, $authType = null);`


I recommend specifying the version also.
`new SurveyGizmoApiWrapper($userId = surveygizmo.key, $secret = null, $authType = null, $opts = ['version' => 'v5']);`

**Comment by spacenate** [comment]
Hey Freak! Thank you for submitting this issue, and for updating it with a possible solution. I apologize for the partially-abandoned status of this repo – I haven't had nearly as many chances to put this wrapper to use in my day-to-day work lately.

If you care to submit a pull request with any suggested changes (I see you've updated tests in your fork), I'd be happy to look them over and pull them in. Regardless, I hope you've found this wrapper helpful in some way :)

**Comment by spacenate** [comment]
I've updated this wrapper to reference only api_token and oath authentication methods. I changed the default version to V5 as well.
