### ISSUE TITLE
Can't Adjust SurveyResponse getList results per page.

### ISSUE THREAD

**Issue by freak3dot** [spacenate/surveygizmo-api-php#7]
My surveyResponse->getList currently returns 370 pages with the default page size of 50 per page.

Survey Gizmo v5 now allows a parameter resultsperpage which allows for a max of 500 with a default of 50.
Source: https://apihelp.surveygizmo.com/help/filters-v5 (Browsing Survey Responses Section)

Do you have any plans to support this parameter?

I'm also going to look at filtering by date as a complementary way to fix my issue.

**Comment by spacenate** [comment]
Sure 👍
