### ISSUE TITLE
Git Tagging for Versioning.

### ISSUE THREAD

**Issue by freak3dot** [spacenate/surveygizmo-api-php#9]
Can you release a tag with the current version of the code in dev-master?

The reason for this request is that a recent change broke some production code. So, when I did a composer update a couple weeks ago. The addition of the resultsperpage parameter had my $filter going into the $limit parameter forSurveyResponse->getList. Yes, I am the same developer who requested that change in #7, doh. 

I'd like to lock in the current version in dev-master to prevent this in the future. Can you tag a new release so that I can use it in my composer.json file?

**Comment by spacenate** [comment]
Hello! Sorry for the delay. Yes, I would be happy to do that. I am writing this from my phone, so I will take a look tomorrow when I have my laptop.

**Comment by spacenate** [comment]
v0.5 tag created 👍
